// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qewzagvxsymtywjwkicf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFld3phZ3Z4c3ltdHl3andraWNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5ODExODEsImV4cCI6MjA3MzU1NzE4MX0.hmCENCerhBB6rof1iFybWOQiteEODoxxYKDLloLTz1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});